---
- name: Install Docker Engine
  hosts: k8s_cluster
  become: true
  become_user: root
  tasks:
    - name: Install requirement packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Download Docker installation script
      ansible.builtin.shell:
        cmd: curl -fsSL https://get.docker.com -o /tmp/install_docker.sh

    - name: Execute Docker installation script
      ansible.builtin.shell:
        cmd: sudo sh /tmp/install_docker.sh

