- name: Install k3s in one host
  hosts: k3s_cluster
  become: true
  become_user: root
  # serial: "50%"
  gather_facts: False
  tasks:
    - name: Get ip
      ansible.builtin.shell:
        cmd: hostname -I | awk '{print $1}'
      register: k3s_ip_address
    - name: Set K3s_SERVER_IP
      ansible.builtin.set_fact:
        K3s_SERVER_IP: '{{ k3s_ip_address.stdout }}'
    - name: install
      ansible.builtin.shell:
        cmd: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--tls-san {{ K3s_SERVER_IP }}" sh -
    - name: Copy kubeconfig from the server to local/bastions host
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ~/.kube
